package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author CAMPUSRP-LAB\09816655608
 */
public class FrAtendente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrAtendente.class.getName());
    private javax.swing.JFrame telaAnterior;

    public void setTelaAnterior(javax.swing.JFrame tela) {
        this.telaAnterior = tela;
    }

    /**
     * Creates new form FrAtendente
     */
    public FrAtendente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnGerarPagamento = new javax.swing.JButton();
        btnMarcarConsulta = new javax.swing.JButton();
        btnVerAgenda = new javax.swing.JButton();
        btnGerenciarComunidade = new javax.swing.JButton();
        btnVizualizarExtrato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarGestante = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        btnGerarPagamento.setText("GERAR PAGAMENTO");
        btnGerarPagamento.addActionListener(this::btnGerarPagamentoActionPerformed);

        btnMarcarConsulta.setText("GERENCIAR CONSULTA");
        btnMarcarConsulta.addActionListener(this::btnMarcarConsultaActionPerformed);

        btnVerAgenda.setText("VER AGENDA");
        btnVerAgenda.addActionListener(this::btnVerAgendaActionPerformed);

        btnGerenciarComunidade.setText("GERENCIAR COMUNIDADE");
        btnGerenciarComunidade.addActionListener(this::btnGerenciarComunidadeActionPerformed);

        btnVizualizarExtrato.setText("VIZUALIZAR EXTRATO");
        btnVizualizarExtrato.addActionListener(this::btnVizualizarExtratoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel1.setText("OLÁ...");

        btnCadastrarGestante.setText("CADASTRAR USUARIO");
        btnCadastrarGestante.addActionListener(this::btnCadastrarGestanteActionPerformed);

        btnVoltar.setText("SAIR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGerenciarComunidade, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(btnMarcarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVizualizarExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrarGestante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarGestante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerenciarComunidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMarcarConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVizualizarExtrato)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPagamentoActionPerformed
        views.FrFormaPagamento telaNova = new views.FrFormaPagamento();

        telaNova.setTelaAnterior(this);

        telaNova.setLocationRelativeTo(null);
        telaNova.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_btnGerarPagamentoActionPerformed

    private void btnCadastrarGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarGestanteActionPerformed
    FrCadUsuario telaCadastro = new FrCadUsuario();
    telaCadastro.setTelaAnterior(this);
    telaCadastro.pack();
    telaCadastro.setLocationRelativeTo(null);
    telaCadastro.setResizable(false);
    telaCadastro.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarGestanteActionPerformed

    private void btnGerenciarComunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarComunidadeActionPerformed
        FrComunidade telaComunidade = new FrComunidade();
        telaComunidade.setTelaAnterior(this);
        telaComunidade.setLocationRelativeTo(null);
        telaComunidade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGerenciarComunidadeActionPerformed

    private void btnMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarConsultaActionPerformed
        FrConsulta telaConsulta = new FrConsulta();
        telaConsulta.setTelaAnterior(this);
        telaConsulta.setLocationRelativeTo(null);
        telaConsulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMarcarConsultaActionPerformed

    private void btnVerAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAgendaActionPerformed
        FrAgenda telaAgenda = new FrAgenda();
        telaAgenda.setTelaAnterior(this);
        telaAgenda.setLocationRelativeTo(null);
        telaAgenda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerAgendaActionPerformed

    private void btnVizualizarExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarExtratoActionPerformed
        FrExtrato telaExtrato = new FrExtrato();
        telaExtrato.setTelaAnterior(this);
        telaExtrato.setLocationRelativeTo(null);
        telaExtrato.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVizualizarExtratoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();

        views.LoginV2 telaLogin = new views.LoginV2();
        telaLogin.setLocationRelativeTo(null);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrAtendente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarGestante;
    private javax.swing.JButton btnGerarPagamento;
    private javax.swing.JButton btnGerenciarComunidade;
    private javax.swing.JButton btnMarcarConsulta;
    private javax.swing.JButton btnVerAgenda;
    private javax.swing.JButton btnVizualizarExtrato;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
