package views;

import controller.GestanteController;
import controller.UsuarioController;
import dao.UsuarioDAO;
import entidades.Gestante;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 09816655608
 */
public class FrCadGestante extends javax.swing.JFrame {

    private javax.swing.JFrame telaAnterior;

    private String nomeBase;
    private String cpfBase;
    private String loginBase;
    private String senhaBase;
    private String emailBase;
    private String dataNasc;
    private String contato;
    private String idade;

    private String cpfGestanteEdicao = null;

    private void limparFormulario() {
        txtDiaDaDescoberta.setText("");
        txtSemanasDeGravidez.setText("");
        txtPrevisaoDoParto.setText("");
        BtnGravidezDeRisco.setSelected(false);
        cpfGestanteEdicao = null;
    }

    private void habilitarFormulario(boolean habilitar) {
        txtDiaDaDescoberta.setEnabled(habilitar);
        txtSemanasDeGravidez.setEnabled(habilitar);
        txtPrevisaoDoParto.setEnabled(habilitar);
        BtnGravidezDeRisco.setEnabled(habilitar);
    }

    public FrCadGestante(String nome, String cpf, String login, String senha, String email, String dataNasc, String contato, String idade) {
        initComponents();
        setLocationRelativeTo(null);

        this.nomeBase = nome;
        this.cpfBase = cpf;
        this.loginBase = login;
        this.senhaBase = senha;
        this.emailBase = email;
        this.dataNasc = dataNasc;
        this.contato = contato;
        this.idade = idade;
    }

    public void setTelaAnterior(javax.swing.JFrame tela) {
        this.telaAnterior = tela;
    }

    public FrCadGestante() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiaDaDescoberta = new javax.swing.JTextField();
        txtSemanasDeGravidez = new javax.swing.JTextField();
        txtPrevisaoDoParto = new javax.swing.JTextField();
        BtnGravidezDeRisco = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCriarGestante = new javax.swing.JButton();
        btnEditarGestante = new javax.swing.JButton();
        btnApagarGestante = new javax.swing.JButton();
        btnSalvarGestante = new javax.swing.JButton();
        btnLimparGestante = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrador = new javax.swing.JTextArea();

        jToggleButton1.setText("SIM");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("DIA DA DESCOBERTA: ");

        jLabel5.setText("SEMANAS DE GRAVIDEZ:");

        jLabel7.setText("GRAVIDEZ DE RISCO: ");

        txtDiaDaDescoberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaDaDescobertaActionPerformed(evt);
            }
        });

        BtnGravidezDeRisco.setText("SIM");

        jLabel8.setText("PREVISAO DO PARTO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrevisaoDoParto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGravidezDeRisco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDiaDaDescoberta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(txtSemanasDeGravidez, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaDaDescoberta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSemanasDeGravidez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtPrevisaoDoParto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGravidezDeRisco)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE GESTANTE ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        btnCriarGestante.setText("CRIAR");
        btnCriarGestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGestanteActionPerformed(evt);
            }
        });

        btnEditarGestante.setText("EDITAR");
        btnEditarGestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGestanteActionPerformed(evt);
            }
        });

        btnApagarGestante.setText("APAGAR");
        btnApagarGestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarGestanteActionPerformed(evt);
            }
        });

        btnSalvarGestante.setText("SALVAR");
        btnSalvarGestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGestanteActionPerformed(evt);
            }
        });

        btnLimparGestante.setText("LIMPAR");
        btnLimparGestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparGestanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarGestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarGestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApagarGestante)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarGestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparGestante)
                .addGap(100, 100, 100))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarGestante)
                    .addComponent(btnEditarGestante)
                    .addComponent(btnApagarGestante)
                    .addComponent(btnSalvarGestante)
                    .addComponent(btnLimparGestante))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        mostrador.setColumns(20);
        mostrador.setRows(5);
        jScrollPane1.setViewportView(mostrador);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtDiaDaDescobertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaDaDescobertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaDaDescobertaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnCriarGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGestanteActionPerformed
    this.limparFormulario();
        this.habilitarFormulario(true);     
    }//GEN-LAST:event_btnCriarGestanteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();

        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGestanteActionPerformed
        try {
            UsuarioDAO dao = new UsuarioDAO();

            if (cpfGestanteEdicao != null) {
                entidades.Usuario usuario = dao.buscarObjetoPorCpf(cpfGestanteEdicao);

                if (usuario instanceof entidades.Gestante) {
                    entidades.Gestante gestante = (entidades.Gestante) usuario;

                    gestante.setDiaDaDescoberta(txtDiaDaDescoberta.getText());
                    gestante.setSemanasDeGravidez(txtSemanasDeGravidez.getText());
                    gestante.setPrevisaoDoParto(txtPrevisaoDoParto.getText());
                    gestante.setGravidezDeRisco(BtnGravidezDeRisco.isSelected() ? "Sim" : "Não");

                    dao.editar(gestante);
                    JOptionPane.showMessageDialog(this, "Gestante atualizada com sucesso!");

                    this.limparFormulario();
                    this.habilitarFormulario(false);
                    return;
                }
            }

            String risco = BtnGravidezDeRisco.isSelected() ? "Sim" : "Não";

            GestanteController controller = new GestanteController();
            controller.cadastrar(
                    nomeBase, cpfBase, loginBase, senhaBase, emailBase,
                    dataNasc, contato, idade,
                    txtDiaDaDescoberta.getText(), txtSemanasDeGravidez.getText(),
                    txtPrevisaoDoParto.getText(), risco
            );

            JOptionPane.showMessageDialog(this, "Gestante cadastrada com sucesso!");

            this.dispose();
            if (this.telaAnterior != null) {
                this.telaAnterior.setVisible(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarGestanteActionPerformed

    private void btnApagarGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarGestanteActionPerformed
        String cpfDigitado = JOptionPane.showInputDialog(this, "Digite o CPF do usuário que deseja apagar:", "Excluir Usuário", JOptionPane.QUESTION_MESSAGE);

        if (cpfDigitado != null && !cpfDigitado.trim().isEmpty()) {
            try {
                UsuarioDAO dao = new UsuarioDAO();
                String nomeEncontrado = dao.buscarNomePorCpf(cpfDigitado.trim());

                if (nomeEncontrado == null) {
                    JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado com o CPF: " + cpfDigitado, "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String mensagem = "Deseja realmente excluir este usuário?\n\n"
                        + "Nome: " + nomeEncontrado + "\n"
                        + "CPF: " + cpfDigitado.trim();

                int resposta = JOptionPane.showConfirmDialog(
                        this,
                        mensagem,
                        "Confirmar Exclusão",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    UsuarioController controller = new UsuarioController();
                    controller.excluirPorCpf(cpfDigitado.trim());

                    JOptionPane.showMessageDialog(this, "Usuário apagado com sucesso!");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao apagar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarGestanteActionPerformed

    private void btnEditarGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGestanteActionPerformed
        String cpfDigitado = JOptionPane.showInputDialog(this, "Digite o CPF da gestante para editar:", "Editar Gestante", JOptionPane.QUESTION_MESSAGE);

        if (cpfDigitado != null && !cpfDigitado.trim().isEmpty()) {
            try {
                UsuarioDAO dao = new UsuarioDAO();
                entidades.Usuario usuario = dao.buscarObjetoPorCpf(cpfDigitado.trim());

                if (usuario instanceof entidades.Gestante) {
                    entidades.Gestante gestante = (entidades.Gestante) usuario;

                    this.limparFormulario();
                    this.habilitarFormulario(true);

                    cpfGestanteEdicao = gestante.getCpf();

                    txtDiaDaDescoberta.setText(gestante.getDiaDaDescoberta());
                    txtSemanasDeGravidez.setText(gestante.getSemanasDeGravidez());
                    txtPrevisaoDoParto.setText(gestante.getPrevisaoDoParto());
                    BtnGravidezDeRisco.setSelected("Sim".equalsIgnoreCase(gestante.getGravidezDeRisco()));

                    JOptionPane.showMessageDialog(this, "Dados da gestante carregados para edição!");
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhuma gestante encontrada com este CPF.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarGestanteActionPerformed

    private void btnLimparGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparGestanteActionPerformed
  this.limparFormulario();
  // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparGestanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadGestante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadGestante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadGestante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadGestante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadGestante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnGravidezDeRisco;
    private javax.swing.JButton btnApagarGestante;
    private javax.swing.JButton btnCriarGestante;
    private javax.swing.JButton btnEditarGestante;
    private javax.swing.JButton btnLimparGestante;
    private javax.swing.JButton btnSalvarGestante;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea mostrador;
    private javax.swing.JTextField txtDiaDaDescoberta;
    private javax.swing.JTextField txtPrevisaoDoParto;
    private javax.swing.JTextField txtSemanasDeGravidez;
    // End of variables declaration//GEN-END:variables
}
