package views;

import controller.GerenteController;
import controller.UsuarioController;
import dao.UsuarioDAO;
import entidades.Gerente;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 09816655608
 */
public class FrCadGerente extends javax.swing.JFrame {

    private javax.swing.JFrame telaAnterior;
    private String nomeBase;
    private String cpfBase;
    private String loginBase;
    private String senhaBase;
    private String emailBase;
    private String dataNasc;
    private String contato;
    private String idade;

    private String cpfGerenteEdicao = null;

    private void limparFormulario() {
        checkAcessoTotal.setSelected(false);
        cpfGerenteEdicao = null;
    }

    private void habilitarFormulario(boolean habilitar) {
        checkAcessoTotal.setEnabled(habilitar);
    }

    FrCadGerente(String nome, String cpf, String login, String senha, String email, String dataNasc, String contato, String idade) {
        initComponents();
        setLocationRelativeTo(null);

        this.nomeBase = nome;
        this.cpfBase = cpf;
        this.loginBase = login;
        this.senhaBase = senha;
        this.emailBase = email;
        this.dataNasc = dataNasc;
        this.contato = contato;
        this.idade = idade;
    }

    public void setTelaAnterior(javax.swing.JFrame tela) {
        this.telaAnterior = tela;
    }

    /**
     * Creates new form FrCadGerente
     */
    public FrCadGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkAcessoTotal = new javax.swing.JCheckBox();
        btnVoltar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCriarMedico = new javax.swing.JButton();
        btnEditarMedico = new javax.swing.JButton();
        btnApagarMedico = new javax.swing.JButton();
        btnSalvarMedico = new javax.swing.JButton();
        btnLimparMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE GERENTE");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setText("DEFINIR PERMISSOES");

        checkAcessoTotal.setText("ACESSO TOTAL ");
        checkAcessoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAcessoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(checkAcessoTotal)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAcessoTotal)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        btnCriarMedico.setText("CRIAR");
        btnCriarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarMedicoActionPerformed(evt);
            }
        });

        btnEditarMedico.setText("EDITAR");
        btnEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedicoActionPerformed(evt);
            }
        });

        btnApagarMedico.setText("APAGAR");
        btnApagarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarMedicoActionPerformed(evt);
            }
        });

        btnSalvarMedico.setText("SALVAR");
        btnSalvarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMedicoActionPerformed(evt);
            }
        });

        btnLimparMedico.setText("LIMPAR");
        btnLimparMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApagarMedico)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparMedico)
                .addGap(100, 100, 100))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarMedico)
                    .addComponent(btnEditarMedico)
                    .addComponent(btnApagarMedico)
                    .addComponent(btnSalvarMedico)
                    .addComponent(btnLimparMedico))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAcessoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAcessoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAcessoTotalActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();

        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCriarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarMedicoActionPerformed
       this.limparFormulario();
        this.habilitarFormulario(true);         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarMedicoActionPerformed

    private void btnSalvarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMedicoActionPerformed
        try {
            UsuarioDAO dao = new UsuarioDAO();

            // 1. SE ESTIVER EDITANDO (CPF preenchido pelo botão Editar)
            if (cpfGerenteEdicao != null) {
                entidades.Usuario usuario = dao.buscarObjetoPorCpf(cpfGerenteEdicao);

                if (usuario instanceof entidades.Gerente) {
                    entidades.Gerente gerente = (entidades.Gerente) usuario;

                    checkAcessoTotal.setSelected("TOTAL".equalsIgnoreCase(gerente.getNivelAcesso()));

                    dao.editar(gerente);
                    JOptionPane.showMessageDialog(this, "Gerente atualizado com sucesso!");
                    gerente.setNivelAcesso(checkAcessoTotal.isSelected() ? "TOTAL" : "NORMAL");
                    this.limparFormulario();
                    this.habilitarFormulario(false);
                    return;
                }
            }

            String acessoTotal = checkAcessoTotal.isSelected() ? "TOTAL" : "NORMAL";

            GerenteController controller = new GerenteController();
            controller.cadastrar(
                    nomeBase, cpfBase, loginBase, senhaBase, emailBase,
                    dataNasc, contato, idade,
                    acessoTotal
            );

            JOptionPane.showMessageDialog(this, "Gerente cadastrado com sucesso!");

            this.dispose();
            if (this.telaAnterior != null) {
                this.telaAnterior.setVisible(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarMedicoActionPerformed

    private void btnApagarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarMedicoActionPerformed
        String cpfDigitado = JOptionPane.showInputDialog(this, "Digite o CPF do usuário que deseja apagar:", "Excluir Usuário", JOptionPane.QUESTION_MESSAGE);

        if (cpfDigitado != null && !cpfDigitado.trim().isEmpty()) {
            try {
                UsuarioDAO dao = new UsuarioDAO();
                String nomeEncontrado = dao.buscarNomePorCpf(cpfDigitado.trim());

                if (nomeEncontrado == null) {
                    JOptionPane.showMessageDialog(this, "Nenhum usuário encontrado com o CPF: " + cpfDigitado, "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String mensagem = "Deseja realmente excluir este usuário?\n\n"
                        + "Nome: " + nomeEncontrado + "\n"
                        + "CPF: " + cpfDigitado.trim();

                int resposta = JOptionPane.showConfirmDialog(
                        this,
                        mensagem,
                        "Confirmar Exclusão",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    UsuarioController controller = new UsuarioController();
                    controller.excluirPorCpf(cpfDigitado.trim());

                    JOptionPane.showMessageDialog(this, "Usuário apagado com sucesso!");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao apagar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarMedicoActionPerformed

    private void btnEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicoActionPerformed
        String cpfDigitado = JOptionPane.showInputDialog(this, "Digite o CPF do gerente para editar:", "Editar Gerente", JOptionPane.QUESTION_MESSAGE);

        if (cpfDigitado != null && !cpfDigitado.trim().isEmpty()) {
            try {
                UsuarioDAO dao = new UsuarioDAO();
                entidades.Usuario usuario = dao.buscarObjetoPorCpf(cpfDigitado.trim());

                if (usuario instanceof entidades.Gerente) {
                    entidades.Gerente gerente = (entidades.Gerente) usuario;

                    this.limparFormulario();
                    this.habilitarFormulario(true);

                    cpfGerenteEdicao = gerente.getCpf();

                    
                   checkAcessoTotal.setSelected("SIM".equalsIgnoreCase(gerente.getNivelAcesso()));

                    JOptionPane.showMessageDialog(this, "Dados do gerente carregados para edição!");
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhum gerente encontrado com este CPF.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMedicoActionPerformed

    private void btnLimparMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparMedicoActionPerformed
   this.limparFormulario();
        this.habilitarFormulario(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarMedico;
    private javax.swing.JButton btnCriarMedico;
    private javax.swing.JButton btnEditarMedico;
    private javax.swing.JButton btnLimparMedico;
    private javax.swing.JButton btnSalvarMedico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox checkAcessoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
