package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CAMPUSRP-LAB\09816655608
 */
public class FrComunidade extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrComunidade.class.getName());
    private javax.swing.JFrame telaAnterior;

    public void setTelaAnterior(javax.swing.JFrame tela) {
        this.telaAnterior = tela;
    }

    /**
     * Creates new form FrComunidade
     */
    public FrComunidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrarNaAbaDeInformacoes = new javax.swing.JButton();
        btnEntrarNoForumDeApoioDasGestante = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnVerInformacoes = new javax.swing.JButton();
        btnVerForum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel1.setText("SEJA BEM VINDO A COMUNIDADE");

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        jLabel2.setText("ESCOLHA UMA AÇÃO");

        btnEntrarNaAbaDeInformacoes.setText("ENTRAR NA ABA DE INFORMAÇOES ");
        btnEntrarNaAbaDeInformacoes.addActionListener(this::btnEntrarNaAbaDeInformacoesActionPerformed);

        btnEntrarNoForumDeApoioDasGestante.setText("ENTRAR NO FORUM DE APOIO DAS GESTANTES");
        btnEntrarNoForumDeApoioDasGestante.addActionListener(this::btnEntrarNoForumDeApoioDasGestanteActionPerformed);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnVerInformacoes.setText("VER INFORMAÇOES ");
        btnVerInformacoes.addActionListener(this::btnVerInformacoesActionPerformed);

        btnVerForum.setText("VER FORUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEntrarNaAbaDeInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEntrarNoForumDeApoioDasGestante, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(btnVerInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerForum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnVoltar))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(btnEntrarNaAbaDeInformacoes)
                .addGap(18, 18, 18)
                .addComponent(btnEntrarNoForumDeApoioDasGestante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerInformacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerForum)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarNaAbaDeInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarNaAbaDeInformacoesActionPerformed
        views.FrComunidadeInfo telaInfo = new views.FrComunidadeInfo();
        telaInfo.setLocationRelativeTo(null); // Centraliza no ecrã
        telaInfo.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarNaAbaDeInformacoesActionPerformed

    private void btnEntrarNoForumDeApoioDasGestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarNoForumDeApoioDasGestanteActionPerformed
        views.FrComunidadeMural telaForum = new views.FrComunidadeMural();
        telaForum.setLocationRelativeTo(null);
        telaForum.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarNoForumDeApoioDasGestanteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       this.dispose(); // Fecha o Pix
        
        // Esta é a parte que falta se o programa está a fechar todo!
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVerInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInformacoesActionPerformed
        FrVerComunidadeInfo telaVerComunidadeInfo = new FrVerComunidadeInfo();
// telaVerComunidadeInfo.pack();
        telaVerComunidadeInfo.setLocationRelativeTo(null);
        telaVerComunidadeInfo.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnVerInformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrComunidade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarNaAbaDeInformacoes;
    private javax.swing.JButton btnEntrarNoForumDeApoioDasGestante;
    private javax.swing.JButton btnVerForum;
    private javax.swing.JButton btnVerInformacoes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
