package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CAMPUSRP-LAB\09816655608
 */
public class FrMedico extends javax.swing.JFrame {
        private javax.swing.JFrame telaAnterior;

    public void setTelaAnterior(javax.swing.JFrame tela) {
        this.telaAnterior = tela;
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrMedico.class.getName());

    /**
     * Creates new form FrMedico
     */
    public FrMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVizualizarAgenda = new javax.swing.JButton();
        btnRegistrarExames = new javax.swing.JButton();
        btnAcessarPronturarios = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel1.setText("OLÁ...");

        btnVizualizarAgenda.setText("VIZUALIZAR AGENDA");
        btnVizualizarAgenda.addActionListener(this::btnVizualizarAgendaActionPerformed);

        btnRegistrarExames.setText("PEDIDO DE EXAME");
        btnRegistrarExames.addActionListener(this::btnRegistrarExamesActionPerformed);

        btnAcessarPronturarios.setText("ACESSAR PRONTUARIOS ");
        btnAcessarPronturarios.addActionListener(this::btnAcessarPronturariosActionPerformed);

        btnVoltar.setText("SAIR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarExames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVizualizarAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcessarPronturarios, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(btnVizualizarAgenda)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarExames)
                .addGap(18, 18, 18)
                .addComponent(btnAcessarPronturarios)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVizualizarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarAgendaActionPerformed
FrAgenda telaAgenda = new FrAgenda();
        telaAgenda.setTelaAnterior(this);
        telaAgenda.setLocationRelativeTo(null);
        telaAgenda.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVizualizarAgendaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
this.dispose(); // Fecha a tela atual
        
        if (this.telaAnterior != null) {
            // Se a tela anterior for o LoginV2, limpamos os campos dela antes de mostrar
            if (this.telaAnterior instanceof LoginV2) {
                ((LoginV2) this.telaAnterior).limparCampos();
            }
            
            this.telaAnterior.setVisible(true); // Reexibe o login limpinho
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRegistrarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarExamesActionPerformed
FrExame telaRegistrarExame = new FrExame(); 
        telaRegistrarExame.setTelaAnterior(this);
        telaRegistrarExame.setLocationRelativeTo(null);
        telaRegistrarExame.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarExamesActionPerformed

    private void btnAcessarPronturariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarPronturariosActionPerformed
FrProntuario telaProntuario = new FrProntuario();
        telaProntuario.setTelaAnterior(this);
        telaProntuario.setLocationRelativeTo(null);
        telaProntuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessarPronturariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarPronturarios;
    private javax.swing.JButton btnRegistrarExames;
    private javax.swing.JButton btnVizualizarAgenda;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
